server: 
  port: 8010
     
       
qingk:
  phoenix:
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: jdbc:phoenix:10.0.219.136
    username:
    password:
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 1
    idle-timeout: 30000
    read-only: false
    connection-timeout: 30000
    max-lifetime: 1800000 
    
  mysql:
    username: root
    password: 123abc
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.49.11:3306/mmsdb_formaldev?autoReconnect=true&useUnicode=true&characterEncoding=utf8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 1
    idle-timeout: 30000
    read-only: false
    connection-timeout: 30000
    max-lifetime: 1800000 
    
  enitypackage: com.allook.statistics.systemservice.enity
  
  redis:
    host: 10.0.219.166
    port: 6380
    database: 2
    max-idle: 8
    min-idle: 0
    max-total: 8
    max-wait: 6000
    test-on-borrow: true
    timeout: 10000
  
spring:   
  data:
    # elasticsearch自动配置
    elasticsearch:
      # 集群名称
      cluster-name: qingkelk
      # 节点列表
      cluster-nodes: 10.0.219.21:9300
      repositories:
        # 是否启用repository
        enabled: true
      properties:
        client:
          transport:
            # 客户端是否去嗅探整个集群的状态，把集群中其它机器的ip地址加到客户端中，这样做的好处是一般你不用手动设置集群里所有集群的ip到连接客户端，它会自动帮你添加，并且自动发现新加入集群的机器
            sniff: true
            # 是否忽略集群名称验证
            ignore_cluster_name: false
            # 设置等待ping命令返回结果时间
            ping_timeout: 5s
            # 节点之间互相ping，互连检测时间间隔
            nodes_sampler_interval: 5s
  application: 
    name: systemservice        
  
            
statistics:
  kafka:
    consumer:
      zookeeper-connect: 10.0.219.165:2180
      zookeeper-session-timeout: 30000
      auto-commit-enable: true
      auto-commit-interval: 1000
      auto-offset-reset: largest
      rebalance-backoff-ms: 2000
      rebalance-max-retries: 10           
      groups:
        StatisticsTestGroup:
          topic: new_statistics_test
          group-id: StatisticsTestGroup
          concurrency: 5
        
    
    producer:
      zookeeper-connect: 10.0.219.165:2180
      kafka-connect: 10.0.219.165:9090 
      
eureka: 
  client: 
    service-url: 
      #defaultZone: http://qkstatistics1.com:8001/eureka/,http://qkstatistics2.com:8002/eureka/,http://qkstatistics3.com:8003/eureka/
      defaultZone: http://qkstatistics1.com:8001/eureka/ 
  
      
 

 